/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra2_dennischirinos_lab6_11611197;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import sun.java2d.pipe.hw.AccelDeviceEventListener;

/**
 *
 * @author denni
 */
public class Frame extends javax.swing.JFrame {

    ArrayList<Carretera> ListaCarreteras = new ArrayList();
    ArrayList<Restaurante> ListaRestaurantes = new ArrayList();
    ArrayList<Cancha> ListaCanchas = new ArrayList();
    ArrayList<Casas> ListaCasas = new ArrayList();
    ArrayList<Lugar> ListaLugares = new ArrayList();
    int NumCarretera;

    /**
     * Creates new form Frame
     */
    public Frame() {
        this.NumCarretera = 0;
        initComponents();
        //
        DefaultMutableTreeNode Raiz = new DefaultMutableTreeNode("Locaciones");
        DefaultTreeModel model;
        DefaultMutableTreeNode Lugares = new DefaultMutableTreeNode("Lugares");
        Raiz.add(Lugares);
        model = (DefaultTreeModel) JTR_Tree.getModel();
        model.setRoot(Raiz);
        CB_Categoria_Res.removeAllItems();
        CB_Categoria_Can.removeAllItems();
        //
        CB_Categoria_Res.addItem("Chino");
        CB_Categoria_Res.addItem("Mexicano");
        CB_Categoria_Res.addItem("Italiano");
        CB_Categoria_Res.addItem("Comida Rapida");
        //
        CB_Categoria_Can.addItem("Football");
        CB_Categoria_Can.addItem("Basquet");
        CB_Categoria_Can.addItem("Tenis");
        CB_Categoria_Can.addItem("Volley");
        //
        jMenuItem6.setText("Remover");
        RBT_Casa.setVisible(false);
//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Crear = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_Valor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA_Direccion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Panel_Res = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CB_Categoria_Res = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SP_Calificacion = new javax.swing.JSpinner();
        Panel_Res1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CB_Categoria_Can = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TF_Estado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RB_Res = new javax.swing.JRadioButton();
        RB_Can = new javax.swing.JRadioButton();
        RB_Casa = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        PopUp_Remove = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        JD_Tabla = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_Tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        RBT_Res = new javax.swing.JRadioButton();
        RBT_Can = new javax.swing.JRadioButton();
        RBT_Casa = new javax.swing.JRadioButton();
        RBT_Car = new javax.swing.JRadioButton();
        JD_Lista = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        JL_Lugares = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        RBL_Res = new javax.swing.JRadioButton();
        RBL_Can = new javax.swing.JRadioButton();
        RBL_Casa = new javax.swing.JRadioButton();
        JD_CrearC = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TF_No = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_Distancia = new javax.swing.JTextField();
        CB_Entrada = new javax.swing.JComboBox<>();
        CB_Salida = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        POPUP_RemoveT = new javax.swing.JPopupMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        JD_PosCer = new javax.swing.JDialog();
        CB_ListaLugares = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        TA_Area = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTR_Tree = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        TF_Nombre.setText("Restaurante");

        jLabel2.setText("Valor");

        TF_Valor.setText("192");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Valor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(TF_Nombre))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_Nombre)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TA_Direccion.setColumns(20);
        TA_Direccion.setRows(5);
        TA_Direccion.setText("Aqui");
        jScrollPane2.setViewportView(TA_Direccion);

        jLabel6.setText("Direccion");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria");

        CB_Categoria_Res.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Calificacion");

        javax.swing.GroupLayout Panel_ResLayout = new javax.swing.GroupLayout(Panel_Res);
        Panel_Res.setLayout(Panel_ResLayout);
        Panel_ResLayout.setHorizontalGroup(
            Panel_ResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CB_Categoria_Res, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SP_Calificacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ResLayout.setVerticalGroup(
            Panel_ResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB_Categoria_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SP_Calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jLabel4.setText("Categoria");

        CB_Categoria_Can.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Estado");

        javax.swing.GroupLayout Panel_Res1Layout = new javax.swing.GroupLayout(Panel_Res1);
        Panel_Res1.setLayout(Panel_Res1Layout);
        Panel_Res1Layout.setHorizontalGroup(
            Panel_Res1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Res1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Res1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Panel_Res1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Res1Layout.createSequentialGroup()
                        .addComponent(CB_Categoria_Can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TF_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_Res1Layout.setVerticalGroup(
            Panel_Res1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Res1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Res1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB_Categoria_Can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Res1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        RB_Res.setText("Restaurante");
        RB_Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_ResActionPerformed(evt);
            }
        });

        RB_Can.setText("Cancha");
        RB_Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_CanActionPerformed(evt);
            }
        });

        RB_Casa.setText("Casa");
        RB_Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_CasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RB_Res)
                    .addComponent(RB_Can)
                    .addComponent(RB_Casa))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_Res)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB_Can, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB_Casa)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_CrearLayout = new javax.swing.GroupLayout(JD_Crear.getContentPane());
        JD_Crear.getContentPane().setLayout(JD_CrearLayout);
        JD_CrearLayout.setHorizontalGroup(
            JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_CrearLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(83, 83, 83)
                .addGroup(JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(JD_CrearLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(JD_CrearLayout.createSequentialGroup()
                        .addComponent(Panel_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_Res1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        JD_CrearLayout.setVerticalGroup(
            JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JD_CrearLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_CrearLayout.createSequentialGroup()
                        .addGroup(JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_CrearLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton3)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CrearLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(JD_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel_Res1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_Res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenuItem2.setText("Remover");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        PopUp_Remove.add(jMenuItem2);

        JT_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JT_Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_TablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JT_Tabla);

        RBT_Res.setText("Restaurantes");
        RBT_Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBT_ResActionPerformed(evt);
            }
        });

        RBT_Can.setText("Canchas");
        RBT_Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBT_CanActionPerformed(evt);
            }
        });

        RBT_Casa.setText("Casas");
        RBT_Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBT_CasaActionPerformed(evt);
            }
        });

        RBT_Car.setText("Carreteras");
        RBT_Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBT_CarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RBT_Res))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBT_Can)
                            .addComponent(RBT_Casa)
                            .addComponent(RBT_Car))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBT_Res)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBT_Can)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBT_Casa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBT_Car)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_TablaLayout = new javax.swing.GroupLayout(JD_Tabla.getContentPane());
        JD_Tabla.getContentPane().setLayout(JD_TablaLayout);
        JD_TablaLayout.setHorizontalGroup(
            JD_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_TablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JD_TablaLayout.setVerticalGroup(
            JD_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_TablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JL_Lugares.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(JL_Lugares);

        RBL_Res.setText("Restaurantes");
        RBL_Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBL_ResActionPerformed(evt);
            }
        });

        RBL_Can.setText("Canchas");
        RBL_Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBL_CanActionPerformed(evt);
            }
        });

        RBL_Casa.setText("Casas");
        RBL_Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBL_CasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RBL_Res))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBL_Can)
                            .addComponent(RBL_Casa))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBL_Res)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBL_Can)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBL_Casa)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_ListaLayout = new javax.swing.GroupLayout(JD_Lista.getContentPane());
        JD_Lista.getContentPane().setLayout(JD_ListaLayout);
        JD_ListaLayout.setHorizontalGroup(
            JD_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JD_ListaLayout.setVerticalGroup(
            JD_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ListaLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JD_ListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Numero");

        TF_No.setEnabled(false);

        jLabel9.setText("Distancia");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Distancia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(TF_No))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_No)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        CB_Entrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EntradaActionPerformed(evt);
            }
        });

        CB_Salida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Entrada");

        jLabel11.setText("Salida");

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearCLayout = new javax.swing.GroupLayout(JD_CrearC.getContentPane());
        JD_CrearC.getContentPane().setLayout(JD_CrearCLayout);
        JD_CrearCLayout.setHorizontalGroup(
            JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CrearCLayout.createSequentialGroup()
                        .addGroup(JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CB_Salida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        JD_CrearCLayout.setVerticalGroup(
            JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_CrearCLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton2)))
                .addGap(19, 19, 19)
                .addGroup(JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_CrearCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenuItem6.setText("jMenuItem6");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        POPUP_RemoveT.add(jMenuItem6);

        CB_ListaLugares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_ListaLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ListaLugaresActionPerformed(evt);
            }
        });

        TA_Area.setColumns(20);
        TA_Area.setRows(5);
        jScrollPane5.setViewportView(TA_Area);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_PosCerLayout = new javax.swing.GroupLayout(JD_PosCer.getContentPane());
        JD_PosCer.getContentPane().setLayout(JD_PosCerLayout);
        JD_PosCerLayout.setHorizontalGroup(
            JD_PosCerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PosCerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_PosCerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_ListaLugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JD_PosCerLayout.setVerticalGroup(
            JD_PosCerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PosCerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_PosCerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_PosCerLayout.createSequentialGroup()
                        .addComponent(CB_ListaLugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton4)
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTR_Tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTR_TreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTR_Tree);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Crear Lugar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Crear Carretera");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Listar En Tabla");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Lista En Lista???");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setText("Posiciones Cercanas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JD_Crear.pack();
        JD_Crear.setVisible(true);
        RB_Res.setSelected(true);
        Panel_Res1.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Nombre = TF_Nombre.getText();
        String Direccion = TA_Direccion.getText();
        int Valor = Integer.parseInt(TF_Valor.getText());
        String Categoria_Res = CB_Categoria_Res.getSelectedItem().toString();
        String Categoria_Can = CB_Categoria_Can.getSelectedItem().toString();
        String Estado = TF_Estado.getText();
        int Calificacion = (Integer) SP_Calificacion.getValue();
        if (RB_Res.isSelected()) {
            if (Valor>5) {
            Valor = 0;
            }
            Restaurante c = new Restaurante(Categoria_Res, Valor, Nombre, Direccion, Calificacion);
            ListaRestaurantes.add(c);
        }
        if (RB_Can.isSelected()) {
            Cancha c = new Cancha(Categoria_Can, Estado, Nombre, Direccion, Calificacion);
            ListaCanchas.add(c);
        }
        if (RB_Casa.isSelected()) {
            Casas c = new Casas(Nombre, Direccion, Valor);
            ListaCasas.add(c);
        }
        TF_Valor.setText("");
        TF_Nombre.setText("");
        TA_Direccion.setText("");
        actualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RB_CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_CanActionPerformed
        RB_Res.setSelected(false);
        RB_Casa.setSelected(false);
        Panel_Res.setVisible(false);
        Panel_Res1.setVisible(true);
    }//GEN-LAST:event_RB_CanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RB_ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_ResActionPerformed
        RB_Can.setSelected(false);
        RB_Casa.setSelected(false);
        Panel_Res.setVisible(true);
        Panel_Res1.setVisible(false);
    }//GEN-LAST:event_RB_ResActionPerformed

    private void RB_CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_CasaActionPerformed
        RB_Can.setSelected(false);
        RB_Res.setSelected(false);
        Panel_Res.setVisible(false);
        Panel_Res1.setVisible(false);
    }//GEN-LAST:event_RB_CasaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int Seguro = JOptionPane.showConfirmDialog(this, "Seguro de remover?");
        System.out.println(Seguro);
        if (Seguro == 0) {
            if (Nodo_Seleccionado.getUserObject() instanceof Restaurante) {
                ListaRestaurantes.remove(Nodo_Seleccionado.getUserObject());
            }
            if (Nodo_Seleccionado.getUserObject() instanceof Cancha) {
                ListaRestaurantes.remove(Nodo_Seleccionado.getUserObject());
            }
            if (Nodo_Seleccionado.getUserObject() instanceof Casas) {
                //ListaRestaurantes.remove(Nodo_Seleccionado.getUserObject());
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JTR_TreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTR_TreeMouseClicked
        if (evt.isMetaDown()) {
            int y = evt.getY();
            int x = evt.getX();
            int row = JTR_Tree.getClosestRowForLocation(evt.getX(), evt.getY());
            Object v1 = JTR_Tree.getSelectionPath().getLastPathComponent();
            Nodo_Seleccionado = (DefaultMutableTreeNode) v1;
            if ((Nodo_Seleccionado.getUserObject() instanceof Lugar)) {
                PopUp_Remove.show(JTR_Tree, x, y);
            }
        }
    }//GEN-LAST:event_JTR_TreeMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JD_Tabla.pack();
        JD_Tabla.setVisible(true);
        DefaultTableModel modelRes = new DefaultTableModel();
        modelRes.addColumn("Nombre");
        modelRes.addColumn("Direccion");
        modelRes.addColumn("Valor");
        modelRes.addColumn("Categoria");
        modelRes.addColumn("Calificacion");
        if (ListaRestaurantes.size() >= 0) {
            Object[] o = new Object[modelRes.getColumnCount()];
            for (int i = 0; i < ListaRestaurantes.size(); i++) {
                o[0] = ListaRestaurantes.get(i).getNombre();
                o[1] = ListaRestaurantes.get(i).getDireccion();
                o[2] = ListaRestaurantes.get(i).getValor();
                o[3] = ListaRestaurantes.get(i).getCategoria();
                o[4] = ListaRestaurantes.get(i).getCalificacion();
                modelRes.addRow(o);
            }
        }
        JT_Tabla.setModel(modelRes);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        JD_Lista.pack();
        JD_Lista.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void RBT_CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBT_CanActionPerformed
        RBT_Res.setSelected(false);
        RBT_Casa.setSelected(false);
        RBT_Car.setSelected(false);
        DefaultTableModel modelCan = new DefaultTableModel();
        modelCan.addColumn("Nombre");
        modelCan.addColumn("Direccion");
        modelCan.addColumn("Valor");
        modelCan.addColumn("Categoria");
        modelCan.addColumn("Estado");
        modelCan.addColumn("Entrada");
        modelCan.addColumn("Salida");
        if (ListaCanchas.size() >= 0) {
            Object[] o = new Object[modelCan.getColumnCount()];
            for (int i = 0; i < ListaCanchas.size(); i++) {
                o[0] = ListaCanchas.get(i).getNombre();
                o[1] = ListaCanchas.get(i).getDireccion();
                o[2] = ListaCanchas.get(i).getValor();
                o[3] = ListaCanchas.get(i).getCategoria();
                o[4] = ListaCanchas.get(i).getEstado();
                o[5] = ListaCanchas.get(i).getEntrada();
                o[6] = ListaCanchas.get(i).getSalida();
                modelCan.addRow(o);
            }
        }
        JT_Tabla.setModel(modelCan);
    }//GEN-LAST:event_RBT_CanActionPerformed

    private void RBT_ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBT_ResActionPerformed
        RBT_Can.setSelected(false);
        RBT_Casa.setSelected(false);
        RBT_Car.setSelected(false);
        DefaultTableModel modelRes = new DefaultTableModel();
        modelRes.addColumn("Nombre");
        modelRes.addColumn("Direccion");
        modelRes.addColumn("Valor");
        modelRes.addColumn("Categoria");
        modelRes.addColumn("Calificacion");
        modelRes.addColumn("Entrada");
        modelRes.addColumn("Salida");
        if (ListaRestaurantes.size() >= 0) {
            Object[] o = new Object[modelRes.getColumnCount()];
            for (int i = 0; i < ListaRestaurantes.size(); i++) {
                o[0] = ListaRestaurantes.get(i).getNombre();
                o[1] = ListaRestaurantes.get(i).getDireccion();
                o[2] = ListaRestaurantes.get(i).getValor();
                o[3] = ListaRestaurantes.get(i).getCategoria();
                o[4] = ListaRestaurantes.get(i).getCalificacion();
                o[5] = ListaRestaurantes.get(i).getEntrada();
                o[6] = ListaRestaurantes.get(i).getSalida();
                modelRes.addRow(o);
            }
        }
        JT_Tabla.setModel(modelRes);
    }//GEN-LAST:event_RBT_ResActionPerformed

    private void RBT_CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBT_CasaActionPerformed
        RBT_Res.setSelected(false);
        RBT_Can.setSelected(false);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Direccion");
        model.addColumn("Valor");
        model.addColumn("Entrada");
        model.addColumn("Salida");
        if (ListaCasas.size() >= 0) {
            Object[] o = new Object[model.getColumnCount()];
            for (int i = 0; i < ListaCasas.size(); i++) {
                o[0] = ListaCasas.get(i).getDireccion();
                o[1] = ListaCasas.get(i).getValor();
                o[2] = ListaCasas.get(i).getEntrada();
                o[3] = ListaCasas.get(i).getSalida();
                model.addRow(o);
            }
        }
        JT_Tabla.setModel(model);
    }//GEN-LAST:event_RBT_CasaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JD_Lista.pack();
        JD_Lista.setVisible(true);
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        for (int i = 0; i < ListaRestaurantes.size(); i++) {
            modelo.add(i, ListaRestaurantes.get(i));
        }

        for (int i = 0; i < ListaCasas.size(); i++) {
            modelo.add(i, ListaCasas.get(i));
        }
        JL_Lugares.setModel(modelo);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void RBL_ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBL_ResActionPerformed
        RBL_Can.setSelected(false);
        RBL_Casa.setSelected(false);
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        for (int i = 0; i < ListaRestaurantes.size(); i++) {
            modelo.add(i, ListaRestaurantes.get(i));
        }
        JL_Lugares.setModel(modelo);
    }//GEN-LAST:event_RBL_ResActionPerformed

    private void RBL_CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBL_CanActionPerformed
        RBL_Res.setSelected(false);
        RBL_Casa.setSelected(false);
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        for (int i = 0; i < ListaCanchas.size(); i++) {
            modelo.add(i, ListaCanchas.get(i));
        }
        JL_Lugares.setModel(modelo);
    }//GEN-LAST:event_RBL_CanActionPerformed

    private void RBL_CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBL_CasaActionPerformed
        RBL_Res.setSelected(false);
        RBL_Can.setSelected(false);
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        for (int i = 0; i < ListaCasas.size(); i++) {
            modelo.add(i, ListaCasas.get(i));
        }
        JL_Lugares.setModel(modelo);
    }//GEN-LAST:event_RBL_CasaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JD_CrearC.pack();
        JD_CrearC.setVisible(true);
        CB_Entrada.removeAllItems();
        CB_Salida.removeAllItems();
        TF_No.setText("" + NumCarretera);
        for (int i = 0; i < ListaRestaurantes.size(); i++) {
            ListaLugares.add(ListaRestaurantes.get(i));
        }
        for (int i = 0; i < ListaCanchas.size(); i++) {
            ListaLugares.add(ListaCanchas.get(i));
        }
        for (int i = 0; i < ListaCasas.size(); i++) {
            ListaLugares.add(ListaCasas.get(i));
        }
        for (int i = 0; i < ListaLugares.size(); i++) {
            CB_Entrada.addItem(ListaLugares.get(i).toString());
            CB_Salida.addItem(ListaLugares.get(i).toString());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int No = Integer.parseInt(TF_No.getText());
        double Dis = Double.parseDouble(TF_Distancia.getText());
        int i3 = CB_Entrada.getSelectedIndex();
        int i2 = CB_Salida.getSelectedIndex();
        Lugar Inicio = ListaLugares.get(i3);
        Lugar Final = ListaLugares.get(i2);
        Carretera c = new Carretera(No, Dis, Inicio, Final);
        for (int i = 0; i < ListaRestaurantes.size(); i++) {
            for (int j = 0; j < ListaLugares.size(); j++) {
                if (ListaLugares.get(j).Nombre.equals(ListaRestaurantes.get(i).getNombre())) {
                    System.out.println("Paso!");
                    ListaRestaurantes.get(i).setEntrada(c);
                    ListaRestaurantes.get(i).setSalida(c);
                }
            }
        }
        for (int i = 0; i < ListaCanchas.size(); i++) {
            for (int j = 0; j < ListaLugares.size(); j++) {
                if (ListaLugares.get(j).Nombre.equals(ListaCanchas.get(i).getNombre())) {
                    System.out.println("Paso!");
                    ListaCanchas.get(i).setEntrada(c);
                    ListaCanchas.get(i).setSalida(c);
                }
            }
        }
        for (int i = 0; i < ListaCasas.size(); i++) {
            for (int j = 0; j < ListaLugares.size(); j++) {
                if (ListaLugares.get(j).Nombre.equals(ListaCasas.get(i).getNombre())) {
                    System.out.println("Paso!");
                    ListaCasas.get(i).setEntrada(c);
                    ListaCasas.get(i).setSalida(c);
                }
            }
        }
        ListaLugares.get(i3).setEntrada(c);
        ListaLugares.get(i2).setSalida(c);
        ListaCarreteras.add(c);
        NumCarretera++;
        TF_No.setText("" + NumCarretera);
        actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JT_TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_TablaMouseClicked
        if (evt.isMetaDown()) {
            int y = evt.getY();
            int x = evt.getX();
            row = JT_Tabla.getSelectedRow();
            System.out.println(row);
            //Object v1 = JTR_Tree.getSelectionPath().getLastPathComponent();
            //Nodo_Seleccionado = (DefaultMutableTreeNode) v1;
            POPUP_RemoveT.show(JD_Tabla, x, y);

        }
    }//GEN-LAST:event_JT_TablaMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        if (row >= 0) {
            int Seguro = JOptionPane.showConfirmDialog(this, "Seguro de remover?");
            if (Seguro == 0) {
                if (RBT_Res.isSelected()) {
                    ListaRestaurantes.remove(row);
                }
                if (RBT_Can.isSelected()) {
                    ListaCanchas.remove(row);
                }
                if (RBT_Casa.isSelected()) {
                    ListaCasas.remove(row);
                }
                if (RBT_Car.isSelected()) {
                    ListaCarreteras.remove(row);
                }
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void RBT_CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBT_CarActionPerformed
        RBT_Can.setSelected(false);
        RBT_Res.setSelected(false);
        RBT_Casa.setSelected(false);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Numero");
        model.addColumn("Distancia");
        model.addColumn("Inicio");
        model.addColumn("Final");
        if (ListaCarreteras.size() >= 0) {
            Object[] o = new Object[model.getColumnCount()];
            for (int i = 0; i < ListaCarreteras.size(); i++) {
                o[0] = ListaCarreteras.get(i).getNumero();
                o[1] = ListaCarreteras.get(i).getDistancia();
                o[2] = ListaCarreteras.get(i).getInicio();
                o[3] = ListaCarreteras.get(i).getFinal();
                model.addRow(o);
            }
        }
        JT_Tabla.setModel(model);

    }//GEN-LAST:event_RBT_CarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JD_PosCer.pack();
        JD_PosCer.setVisible(true);
        ListaLugares.removeAll(ListaCasas);
        for (int i = 0; i < ListaRestaurantes.size(); i++) {
            ListaLugares.add(ListaRestaurantes.get(i));
        }
        for (int i = 0; i < ListaCanchas.size(); i++) {
            ListaLugares.add(ListaCanchas.get(i));
        }
        for (int i = 0; i < ListaCasas.size(); i++) {
            ListaLugares.add(ListaCasas.get(i));
        }
        for (int i = 0; i < ListaLugares.size(); i++) {
            CB_Entrada.addItem(ListaLugares.get(i).toString());
            CB_Salida.addItem(ListaLugares.get(i).toString());
        }
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void CB_ListaLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ListaLugaresActionPerformed
        
    }//GEN-LAST:event_CB_ListaLugaresActionPerformed

    private void CB_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_EntradaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int i = CB_ListaLugares.getSelectedIndex();
       for (int j = 0;j<ListaLugares.size();j++) {
       if (ListaLugares.get(i).Entrada.equals(ListaLugares.get(j))) {}
       TA_Area.setText(ListaLugares.get(i).toString());
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    public void actualizar() {
        DefaultMutableTreeNode Raiz = new DefaultMutableTreeNode("Locaciones");
        DefaultMutableTreeNode Lugares = new DefaultMutableTreeNode("Lugares");
        DefaultMutableTreeNode ND_Restaurantes = new DefaultMutableTreeNode("Restaurantes");
        DefaultMutableTreeNode ND_Canchas = new DefaultMutableTreeNode("Canchas");
        DefaultMutableTreeNode ND_Casas = new DefaultMutableTreeNode("Casas");
        DefaultMutableTreeNode ND_Carreteras = new DefaultMutableTreeNode("Carreteras");
        Raiz.add(Lugares);
        Lugares.add(ND_Restaurantes);
        Lugares.add(ND_Canchas);
        Lugares.add(ND_Casas);
        Raiz.add(ND_Carreteras);
        DefaultTreeModel model = new DefaultTreeModel(Raiz);
        for (int i = 0; i < ListaRestaurantes.size(); i++) {
            Restaurante Res = ListaRestaurantes.get(i);
            DefaultMutableTreeNode Node_Restaurante = new DefaultMutableTreeNode(Res);
            DefaultMutableTreeNode Node_Restaurante_Nombre = new DefaultMutableTreeNode(Res.getNombre());
            DefaultMutableTreeNode Node_Restaurante_Valor = new DefaultMutableTreeNode(Res.getValor());
            DefaultMutableTreeNode Node_Restaurante_Categoria = new DefaultMutableTreeNode(Res.getCategoria());
            DefaultMutableTreeNode Node_Restaurante_Calificacion = new DefaultMutableTreeNode(Res.getCalificacion());
            Node_Restaurante.add(Node_Restaurante_Nombre);
            Node_Restaurante.add(Node_Restaurante_Valor);
            Node_Restaurante.add(Node_Restaurante_Categoria);
            Node_Restaurante.add(Node_Restaurante_Calificacion);
            ND_Restaurantes.add(Node_Restaurante);
        }
        for (int i = 0; i < ListaCanchas.size(); i++) {
            Cancha Can = ListaCanchas.get(i);
            DefaultMutableTreeNode Node_Cancha = new DefaultMutableTreeNode(Can);
            DefaultMutableTreeNode Node_Cancha_Direccion = new DefaultMutableTreeNode(Can.getDireccion());
            DefaultMutableTreeNode Node_Cancha_Valor = new DefaultMutableTreeNode(Can.getValor());
            DefaultMutableTreeNode Node_Cancha_Estado = new DefaultMutableTreeNode(Can.getEstado());
            DefaultMutableTreeNode Node_Cancha_Categoria = new DefaultMutableTreeNode(Can.getCategoria());
            Node_Cancha.add(Node_Cancha_Direccion);
            Node_Cancha.add(Node_Cancha_Valor);
            Node_Cancha.add(Node_Cancha_Estado);
            Node_Cancha.add(Node_Cancha_Categoria);
            ND_Canchas.add(Node_Cancha);
        }
        for (int i = 0; i < ListaCasas.size(); i++) {
            Casas Can = ListaCasas.get(i);
            DefaultMutableTreeNode Node_Casa = new DefaultMutableTreeNode(Can);
            DefaultMutableTreeNode Node_Casa_Direccion = new DefaultMutableTreeNode(Can.getDireccion());
            DefaultMutableTreeNode Node_Casa_Valor = new DefaultMutableTreeNode(Can.getValor());
            Node_Casa.add(Node_Casa_Direccion);
            Node_Casa.add(Node_Casa_Valor);
            ND_Casas.add(Node_Casa);
        }
        for (int i = 0; i < ListaCarreteras.size(); i++) {
            Carretera Can = ListaCarreteras.get(i);
            DefaultMutableTreeNode Node_Carretera = new DefaultMutableTreeNode(Can);
            DefaultMutableTreeNode Node_Car_Num = new DefaultMutableTreeNode(Can.getNumero());
            DefaultMutableTreeNode Node_Car_Dis = new DefaultMutableTreeNode(Can.getDistancia());
            DefaultMutableTreeNode Node_Car_Ini = new DefaultMutableTreeNode(Can.getInicio());
            DefaultMutableTreeNode Node_Car_Fin = new DefaultMutableTreeNode(Can.getFinal());
            Node_Carretera.add(Node_Car_Num);
            Node_Carretera.add(Node_Car_Dis);
            Node_Carretera.add(Node_Car_Ini);
            Node_Carretera.add(Node_Car_Fin);
            ND_Carreteras.add(Node_Carretera);
        }
        JTR_Tree.setModel(null);
        JTR_Tree.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Categoria_Can;
    private javax.swing.JComboBox<String> CB_Categoria_Res;
    private javax.swing.JComboBox<String> CB_Entrada;
    private javax.swing.JComboBox<String> CB_ListaLugares;
    private javax.swing.JComboBox<String> CB_Salida;
    private javax.swing.JDialog JD_Crear;
    private javax.swing.JDialog JD_CrearC;
    private javax.swing.JDialog JD_Lista;
    private javax.swing.JDialog JD_PosCer;
    private javax.swing.JDialog JD_Tabla;
    private javax.swing.JList<String> JL_Lugares;
    private javax.swing.JTree JTR_Tree;
    private javax.swing.JTable JT_Tabla;
    private javax.swing.JPopupMenu POPUP_RemoveT;
    private javax.swing.JPanel Panel_Res;
    private javax.swing.JPanel Panel_Res1;
    private javax.swing.JPopupMenu PopUp_Remove;
    private javax.swing.JRadioButton RBL_Can;
    private javax.swing.JRadioButton RBL_Casa;
    private javax.swing.JRadioButton RBL_Res;
    private javax.swing.JRadioButton RBT_Can;
    private javax.swing.JRadioButton RBT_Car;
    private javax.swing.JRadioButton RBT_Casa;
    private javax.swing.JRadioButton RBT_Res;
    private javax.swing.JRadioButton RB_Can;
    private javax.swing.JRadioButton RB_Casa;
    private javax.swing.JRadioButton RB_Res;
    private javax.swing.JSpinner SP_Calificacion;
    private javax.swing.JTextArea TA_Area;
    private javax.swing.JTextArea TA_Direccion;
    private javax.swing.JTextField TF_Distancia;
    private javax.swing.JTextField TF_Estado;
    private javax.swing.JTextField TF_No;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JTextField TF_Valor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
DefaultMutableTreeNode Nodo_Seleccionado;
    int row;
}
